/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'songName' : IDL.Opt(IDL.Text),
  'audioId' : IDL.Opt(IDL.Text),
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'blobId' : IDL.Text,
  'artistName' : IDL.Opt(IDL.Text),
});
export const Message = IDL.Record({
  'to' : IDL.Principal,
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'isRead' : IDL.Bool,
  'isDeletedForEveryone' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : IDL.Int,
  'caption' : IDL.Text,
  'blobId' : IDL.Text,
  'commentCount' : IDL.Nat,
});
export const Interest = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Profile = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'photoLink' : IDL.Text,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'interests' : IDL.Vec(Interest),
  'isActive' : IDL.Bool,
  'genderPreference' : Gender,
  'gender' : Gender,
  'lastActive' : IDL.Int,
});
export const Reel = IDL.Record({
  'id' : IDL.Nat,
  'songName' : IDL.Opt(IDL.Text),
  'audioId' : IDL.Opt(IDL.Text),
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : IDL.Int,
  'caption' : IDL.Text,
  'blobId' : IDL.Text,
  'commentCount' : IDL.Nat,
  'artistName' : IDL.Opt(IDL.Text),
});
export const FollowRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const Notification = IDL.Record({
  'to' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PasswordResetRequestInfo = IDL.Record({
  'username' : IDL.Text,
  'requestTime' : IDL.Int,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'contentId' : IDL.Nat,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const VisibleInterest = IDL.Record({});
export const InterestDisplayPrefs = IDL.Record({
  'skipGender' : IDL.Bool,
  'showGender' : IDL.Bool,
  'showInterests' : IDL.Bool,
  'visibleInterests' : IDL.Vec(VisibleInterest),
  'showAge' : IDL.Bool,
  'genderPreference' : Gender,
});
export const SearchResult = IDL.Record({
  'photoLink' : IDL.Text,
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFollowRequest' : IDL.Func([IDL.Principal], [], []),
  'adminResetPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'commentOnPost' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'commentOnReel' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createReel' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createStory' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'declineFollowRequest' : IDL.Func([IDL.Principal], [], []),
  'deleteExpiredStories' : IDL.Func([], [], []),
  'deleteMessageForEveryone' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'deleteReel' : IDL.Func([IDL.Nat], [], []),
  'fillSampleData' : IDL.Func([], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAllConversations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Message)))],
      ['query'],
    ),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getAllReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationsWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getFollowRequestStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FollowRequestStatus)],
      ['query'],
    ),
  'getFollowerCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getFollowers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFollowing' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFollowingCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getMyUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPendingFollowRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPendingPasswordResetRequests' : IDL.Func(
      [],
      [IDL.Vec(PasswordResetRequestInfo)],
      ['query'],
    ),
  'getPostComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getReelComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getReelsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Reel)], ['query']),
  'getSecurityQuestion' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getUsernameByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getWhoILiked' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getWhoLikedMe' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'hasCompletedOnboarding' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'likeReel' : IDL.Func([IDL.Nat], [], []),
  'likeUser' : IDL.Func([IDL.Principal], [], []),
  'loginWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'markNotificationAsRead' : IDL.Func([IDL.Int], [], []),
  'registerWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'alreadyRegistered' : IDL.Null,
          'usernameTaken' : IDL.Null,
        }),
      ],
      [],
    ),
  'requestAdminPasswordReset' : IDL.Func([IDL.Text], [], []),
  'resetPasswordWithOtp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'saveCallerUserProfileInfo' : IDL.Func([InterestDisplayPrefs], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'sendFollowRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setOffline' : IDL.Func([], [], []),
  'setOnline' : IDL.Func([], [], []),
  'setSecurityQuestion' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'unlikeReel' : IDL.Func([IDL.Nat], [], []),
  'unlikeUser' : IDL.Func([IDL.Principal], [], []),
  'verifySecurityAnswer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'songName' : IDL.Opt(IDL.Text),
    'audioId' : IDL.Opt(IDL.Text),
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'blobId' : IDL.Text,
    'artistName' : IDL.Opt(IDL.Text),
  });
  const Message = IDL.Record({
    'to' : IDL.Principal,
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'isRead' : IDL.Bool,
    'isDeletedForEveryone' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : IDL.Int,
    'caption' : IDL.Text,
    'blobId' : IDL.Text,
    'commentCount' : IDL.Nat,
  });
  const Interest = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Profile = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'photoLink' : IDL.Text,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'interests' : IDL.Vec(Interest),
    'isActive' : IDL.Bool,
    'genderPreference' : Gender,
    'gender' : Gender,
    'lastActive' : IDL.Int,
  });
  const Reel = IDL.Record({
    'id' : IDL.Nat,
    'songName' : IDL.Opt(IDL.Text),
    'audioId' : IDL.Opt(IDL.Text),
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : IDL.Int,
    'caption' : IDL.Text,
    'blobId' : IDL.Text,
    'commentCount' : IDL.Nat,
    'artistName' : IDL.Opt(IDL.Text),
  });
  const FollowRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Notification = IDL.Record({
    'to' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PasswordResetRequestInfo = IDL.Record({
    'username' : IDL.Text,
    'requestTime' : IDL.Int,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'contentId' : IDL.Nat,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const VisibleInterest = IDL.Record({});
  const InterestDisplayPrefs = IDL.Record({
    'skipGender' : IDL.Bool,
    'showGender' : IDL.Bool,
    'showInterests' : IDL.Bool,
    'visibleInterests' : IDL.Vec(VisibleInterest),
    'showAge' : IDL.Bool,
    'genderPreference' : Gender,
  });
  const SearchResult = IDL.Record({
    'photoLink' : IDL.Text,
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFollowRequest' : IDL.Func([IDL.Principal], [], []),
    'adminResetPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'commentOnPost' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'commentOnReel' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createReel' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createStory' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'declineFollowRequest' : IDL.Func([IDL.Principal], [], []),
    'deleteExpiredStories' : IDL.Func([], [], []),
    'deleteMessageForEveryone' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'deleteReel' : IDL.Func([IDL.Nat], [], []),
    'fillSampleData' : IDL.Func([], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAllConversations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Message)))],
        ['query'],
      ),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getAllReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationsWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getFollowRequestStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FollowRequestStatus)],
        ['query'],
      ),
    'getFollowerCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getFollowers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFollowing' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFollowingCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getMyUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPendingFollowRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPendingPasswordResetRequests' : IDL.Func(
        [],
        [IDL.Vec(PasswordResetRequestInfo)],
        ['query'],
      ),
    'getPostComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getReelComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getReelsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Reel)], ['query']),
    'getSecurityQuestion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getUsernameByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getWhoILiked' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getWhoLikedMe' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'hasCompletedOnboarding' : IDL.Func([], [IDL.Bool], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'likeReel' : IDL.Func([IDL.Nat], [], []),
    'likeUser' : IDL.Func([IDL.Principal], [], []),
    'loginWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'markNotificationAsRead' : IDL.Func([IDL.Int], [], []),
    'registerWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'alreadyRegistered' : IDL.Null,
            'usernameTaken' : IDL.Null,
          }),
        ],
        [],
      ),
    'requestAdminPasswordReset' : IDL.Func([IDL.Text], [], []),
    'resetPasswordWithOtp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'saveCallerUserProfileInfo' : IDL.Func([InterestDisplayPrefs], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'sendFollowRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setOffline' : IDL.Func([], [], []),
    'setOnline' : IDL.Func([], [], []),
    'setSecurityQuestion' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'unlikeReel' : IDL.Func([IDL.Nat], [], []),
    'unlikeUser' : IDL.Func([IDL.Principal], [], []),
    'verifySecurityAnswer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };