/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'contentId' : bigint,
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export type FollowRequestStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Interest { 'id' : bigint, 'name' : string }
export interface InterestDisplayPrefs {
  'skipGender' : boolean,
  'showGender' : boolean,
  'showInterests' : boolean,
  'visibleInterests' : Array<VisibleInterest>,
  'showAge' : boolean,
  'genderPreference' : Gender,
}
export interface Message {
  'to' : Principal,
  'content' : string,
  'from' : Principal,
  'isRead' : boolean,
  'isDeletedForEveryone' : boolean,
  'timestamp' : bigint,
}
export interface Notification {
  'to' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export interface PasswordResetRequestInfo {
  'username' : string,
  'requestTime' : bigint,
}
export interface Post {
  'id' : bigint,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : bigint,
  'caption' : string,
  'blobId' : string,
  'commentCount' : bigint,
}
export interface Profile {
  'id' : bigint,
  'bio' : string,
  'photoLink' : string,
  'principal' : Principal,
  'displayName' : string,
  'interests' : Array<Interest>,
  'isActive' : boolean,
  'genderPreference' : Gender,
  'gender' : Gender,
  'lastActive' : bigint,
}
export interface Reel {
  'id' : bigint,
  'songName' : [] | [string],
  'audioId' : [] | [string],
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : bigint,
  'caption' : string,
  'blobId' : string,
  'commentCount' : bigint,
  'artistName' : [] | [string],
}
export interface SearchResult {
  'photoLink' : string,
  'principal' : Principal,
  'username' : string,
  'displayName' : string,
}
export interface Story {
  'id' : bigint,
  'songName' : [] | [string],
  'audioId' : [] | [string],
  'author' : Principal,
  'timestamp' : bigint,
  'blobId' : string,
  'artistName' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VisibleInterest = {};
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFollowRequest' : ActorMethod<[Principal], undefined>,
  'adminResetPassword' : ActorMethod<[string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'commentOnPost' : ActorMethod<[bigint, string], bigint>,
  'commentOnReel' : ActorMethod<[bigint, string], bigint>,
  'createPost' : ActorMethod<[string, string], bigint>,
  'createReel' : ActorMethod<
    [string, string, [] | [string], [] | [string], [] | [string]],
    bigint
  >,
  'createStory' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [string]],
    bigint
  >,
  'declineFollowRequest' : ActorMethod<[Principal], undefined>,
  'deleteExpiredStories' : ActorMethod<[], undefined>,
  'deleteMessageForEveryone' : ActorMethod<[Principal, bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'deleteReel' : ActorMethod<[bigint], undefined>,
  'fillSampleData' : ActorMethod<[], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getActiveStories' : ActorMethod<[], Array<Story>>,
  'getAllConversations' : ActorMethod<[], Array<[Principal, Array<Message>]>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getAllReels' : ActorMethod<[], Array<Reel>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationsWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getFollowRequestStatus' : ActorMethod<
    [Principal],
    [] | [FollowRequestStatus]
  >,
  'getFollowerCount' : ActorMethod<[], bigint>,
  'getFollowers' : ActorMethod<[], Array<Principal>>,
  'getFollowing' : ActorMethod<[], Array<Principal>>,
  'getFollowingCount' : ActorMethod<[], bigint>,
  'getMyProfile' : ActorMethod<[], [] | [Profile]>,
  'getMyUsername' : ActorMethod<[], [] | [string]>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingFollowRequests' : ActorMethod<[], Array<Principal>>,
  'getPendingPasswordResetRequests' : ActorMethod<
    [],
    Array<PasswordResetRequestInfo>
  >,
  'getPostComments' : ActorMethod<[bigint], Array<Comment>>,
  'getPostsByUser' : ActorMethod<[Principal], Array<Post>>,
  'getReelComments' : ActorMethod<[bigint], Array<Comment>>,
  'getReelsByUser' : ActorMethod<[Principal], Array<Reel>>,
  'getSecurityQuestion' : ActorMethod<[string], [] | [string]>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], Profile>,
  'getUsernameByPrincipal' : ActorMethod<[Principal], [] | [string]>,
  'getWhoILiked' : ActorMethod<[], Array<Principal>>,
  'getWhoLikedMe' : ActorMethod<[], Array<Principal>>,
  'hasCompletedOnboarding' : ActorMethod<[], boolean>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isAuthenticated' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'likeReel' : ActorMethod<[bigint], undefined>,
  'likeUser' : ActorMethod<[Principal], undefined>,
  'loginWithCredentials' : ActorMethod<[string, string], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'registerWithCredentials' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'alreadyRegistered' : null } |
      { 'usernameTaken' : null }
  >,
  'requestAdminPasswordReset' : ActorMethod<[string], undefined>,
  'resetPasswordWithOtp' : ActorMethod<[string, string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'saveCallerUserProfileInfo' : ActorMethod<[InterestDisplayPrefs], undefined>,
  'searchUsers' : ActorMethod<[string], Array<SearchResult>>,
  'sendFollowRequest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'setOffline' : ActorMethod<[], undefined>,
  'setOnline' : ActorMethod<[], undefined>,
  'setSecurityQuestion' : ActorMethod<[string, string], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'unlikeReel' : ActorMethod<[bigint], undefined>,
  'unlikeUser' : ActorMethod<[Principal], undefined>,
  'verifySecurityAnswer' : ActorMethod<[string, string], [] | [string]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];