/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Interest { 'id' : bigint, 'name' : string }
export interface InterestDisplayPrefs {
  'skipGender' : boolean,
  'showGender' : boolean,
  'showInterests' : boolean,
  'visibleInterests' : Array<VisibleInterest>,
  'showAge' : boolean,
  'genderPreference' : Gender,
}
export interface Message {
  'to' : Principal,
  'content' : string,
  'from' : Principal,
  'isRead' : boolean,
  'timestamp' : bigint,
}
export interface Notification {
  'to' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export interface Profile {
  'id' : bigint,
  'photoLink' : string,
  'principal' : Principal,
  'displayName' : string,
  'interests' : Array<Interest>,
  'isActive' : boolean,
  'genderPreference' : Gender,
  'gender' : Gender,
  'lastActive' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VisibleInterest = {};
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'fillSampleData' : ActorMethod<[], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllConversations' : ActorMethod<[], Array<[Principal, Array<Message>]>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationsWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getFollowers' : ActorMethod<[], Array<Principal>>,
  'getFollowing' : ActorMethod<[], Array<Principal>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], Profile>,
  'getWhoILiked' : ActorMethod<[], Array<Principal>>,
  'getWhoLikedMe' : ActorMethod<[], Array<Principal>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isAuthenticated' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeUser' : ActorMethod<[Principal], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'saveCallerUserProfileInfo' : ActorMethod<[InterestDisplayPrefs], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'setOffline' : ActorMethod<[], undefined>,
  'setOnline' : ActorMethod<[], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikeUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];