/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Message = IDL.Record({
  'to' : IDL.Principal,
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'isRead' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const Notification = IDL.Record({
  'to' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Interest = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Profile = IDL.Record({
  'id' : IDL.Nat,
  'photoLink' : IDL.Text,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'interests' : IDL.Vec(Interest),
  'isActive' : IDL.Bool,
  'genderPreference' : Gender,
  'gender' : Gender,
  'lastActive' : IDL.Int,
});
export const VisibleInterest = IDL.Record({});
export const InterestDisplayPrefs = IDL.Record({
  'skipGender' : IDL.Bool,
  'showGender' : IDL.Bool,
  'showInterests' : IDL.Bool,
  'visibleInterests' : IDL.Vec(VisibleInterest),
  'showAge' : IDL.Bool,
  'genderPreference' : Gender,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fillSampleData' : IDL.Func([], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllConversations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Message)))],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationsWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getFollowers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFollowing' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getWhoILiked' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getWhoLikedMe' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeUser' : IDL.Func([IDL.Principal], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'saveCallerUserProfileInfo' : IDL.Func([InterestDisplayPrefs], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setOffline' : IDL.Func([], [], []),
  'setOnline' : IDL.Func([], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikeUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Message = IDL.Record({
    'to' : IDL.Principal,
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'isRead' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const Notification = IDL.Record({
    'to' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Interest = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Profile = IDL.Record({
    'id' : IDL.Nat,
    'photoLink' : IDL.Text,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'interests' : IDL.Vec(Interest),
    'isActive' : IDL.Bool,
    'genderPreference' : Gender,
    'gender' : Gender,
    'lastActive' : IDL.Int,
  });
  const VisibleInterest = IDL.Record({});
  const InterestDisplayPrefs = IDL.Record({
    'skipGender' : IDL.Bool,
    'showGender' : IDL.Bool,
    'showInterests' : IDL.Bool,
    'visibleInterests' : IDL.Vec(VisibleInterest),
    'showAge' : IDL.Bool,
    'genderPreference' : Gender,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fillSampleData' : IDL.Func([], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllConversations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Message)))],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationsWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getFollowers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFollowing' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getWhoILiked' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getWhoLikedMe' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeUser' : IDL.Func([IDL.Principal], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'saveCallerUserProfileInfo' : IDL.Func([InterestDisplayPrefs], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setOffline' : IDL.Func([], [], []),
    'setOnline' : IDL.Func([], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikeUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };